[2021-02-18 14:17:49.754] [renderer1] [error] Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:59:86087)
	at Object.dispose (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:9:169648)
	at E.handleConnectionClosed (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:9:169860)
	at E.handleConnectionClosed (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:59:35506)
	at t (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:9:167953)
	at invoke (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:9:312398)
	at o.fire (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:9:313159)
	at X (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:59:75449)
	at invoke (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:9:312398)
	at o.fire (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:9:313159)
	at d.fireClose (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:59:65518)
	at ChildProcess.<anonymous> (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:9:308128)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[2021-02-18 15:00:12.384] [renderer1] [error] Failed to create a temporary file, Unable to resolve non-existing file 'vscode-remote://ssh-remote+adrien2/home/val/python_wkspce/plc_seg/src/models/data_augmentation.py.611829a8f1a26bbc24a09d5f20e03e18.tmp': Error: 
	at new i (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:9:412686)
	at Object.t.getTempFileWithDocumentContents (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:9:340364)

EntryNotFound (FileSystemError): Unable to resolve non-existing file 'vscode-remote://ssh-remote+adrien2/home/val/python_wkspce/plc_seg/src/models/data_augmentation.py.611829a8f1a26bbc24a09d5f20e03e18.tmp'
	at _handleError (/home/val/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/vs/server/remoteExtensionHostProcess.js:86:136165)
	at async y.writeText (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:9:298394)
	at async Object.t.getTempFileWithDocumentContents (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:9:340264)
	at async c.provideDocumentFormattingEdits (/home/val/.vscode-server/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:9:350789)
[2021-02-18 17:15:31.946] [renderer1] [error] Cannot read property 'cmd' of undefined: TypeError: Cannot read property 'cmd' of undefined
	at /home/val/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/vs/server/remoteExtensionHostProcess.js:89:539
	at Array.forEach (<anonymous>)
	at r (/home/val/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/vs/server/remoteExtensionHostProcess.js:89:484)
	at o.findCandidatePorts (/home/val/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/vs/server/remoteExtensionHostProcess.js:89:4027)
	at async o.$registerCandidateFinder (/home/val/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/vs/server/remoteExtensionHostProcess.js:89:1558)
