User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonSendEntireLineToREPL'
User belongs to experiment group 'pythonNotDisplayLinterPrompt'
User belongs to experiment group 'pythonDiscoveryModulecf'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda --version
> conda info --json
Error 2021-04-23 13:16:26: Failed to check if file needs to be fixed EntryNotFound (FileSystemError): Unable to read file '/home/val/python_wkspce/rgd_mice/.vscode/settings.json' (Error: Unable to resolve non-existing file '/home/val/python_wkspce/rgd_mice/.vscode/settings.json')
    at _handleError (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:154942)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at y.readText (/home/val/.vscode/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:9:339523)
    at p.doesFileNeedToBeFixed (/home/val/.vscode/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:59:577126)
    at /home/val/.vscode/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:59:576253
    at async Promise.all (index 1)
    at p.getFilesToBeFixed (/home/val/.vscode/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:59:576199)
    at p.updateTestSettings (/home/val/.vscode/extensions/ms-python.python-2021.4.765268190/out/client/extension.js:59:575826) {
  code: 'FileNotFound'
}
Starting Pylance language server.
Python interpreter path: ~/python_wkspce/hecktor_private/env/bin/python
> conda --version
Python interpreter path: ./env/bin/python3.9
